INSERT INTO users (email,username,password_hash,role) VALUES('user1@mail.com','user1','$2a$10$KZHVTZyyWDKSBlgOfce3xOlWTNqOh7QpOBYAUMWkdn0ey.OEVPGqK','ROLE_USER');
INSERT INTO game (game_name, organizer_id, start_date, end_date) VALUES ('game1', '3', '2022/02/03', '2022/02/11');
INSERT INTO account (user_balance, stock_value, dollar_amount) VALUES ('100000', '0', '100000');
INSERT INTO game_data (user_id, game_id, account_id) VALUES ('3', '1', '1');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'AAPL', '20');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'V', '20');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'CSCO', '25');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'MSFT', '30');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'VOD', '50');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'NVDA', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'INTC', '90');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'ORCL', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'GOOGL', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'AMZN', '7');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'TSM', '12');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'FB', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'KO', '24');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'BABA', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'CVX', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'JPM', '15');
UPDATE account SET (user_balance, stock_value, dollar_amount) = ('104117.66', '74267.21', '29850.45') WHERE account_id = '1';


INSERT INTO users (email,username,password_hash,role) VALUES('user2@mail.com','user2','$2a$10$dYmNhP4uopZmyyfpBzP7keUnpoj3euKS9H/CVtykOGh3lldbiOqOO','ROLE_USER');
INSERT INTO game (game_name, organizer_id, start_date, end_date) VALUES ('game2', '4', '2022/02/04', '2022/02/12');
INSERT INTO account (user_balance, stock_value, dollar_amount) VALUES ('100000', '0', '100000');
INSERT INTO game_data (user_id, game_id, account_id) VALUES ('4', '2', '2');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'AAPL', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'V', '18');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'CSCO', '30');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'MSFT', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'VOD', '45');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'NVDA', '12');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'INTC', '50');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'ORCL', '18');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'GOOGL', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'AMZN', '7');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'TSM', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'FB', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'KO', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'BABA', '12');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'CVX', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'JPM', '18');
UPDATE account SET (user_balance, stock_value, dollar_amount) = ('106394.90', '80921.92', '25474.45') WHERE account_id = '2';


INSERT INTO users (email,username,password_hash,role) VALUES('user3@mail.com','user3','$2a$10$C1AMxXI4frc1yT5l.EonpuX7x3TlI87cRnVbe.g84SHJw97o/pTcO','ROLE_USER');
INSERT INTO game (game_name, organizer_id, start_date, end_date) VALUES ('game3', '5', '2022/02/05', '2022/02/13');
INSERT INTO account (user_balance, stock_value, dollar_amount) VALUES ('100000', '0', '100000');
INSERT INTO game_data (user_id, game_id, account_id) VALUES ('5', '3', '3');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'AAPL', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'V', '36');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'CSCO', '16');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'MSFT', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'VOD', '40');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'NVDA', '20');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'INTC', '35');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'ORCL', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'GOOGL', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'AMZN', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'TSM', '11');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'FB', '7');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'KO', '18');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'BABA', '9');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'CVX', '13');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'ADBE', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('3', 'JPM', '10');
UPDATE account SET (user_balance, stock_value, dollar_amount) = ('101576.68', '79985.20', '21586.83') WHERE account_id = '3';


INSERT INTO users (email,username,password_hash,role) VALUES('user4@mail.com','user4','$2a$10$M6akkOIpRfGMq3pAZX1fU..JAdAqDaP1nLji3ZhX/Sz5QgmEGYI0q','ROLE_USER');
INSERT INTO game (game_name, organizer_id, start_date, end_date) VALUES ('game4', '6', '2022/02/06', '2022/02/14');
INSERT INTO account (user_balance, stock_value, dollar_amount) VALUES ('100000', '0', '100000');
INSERT INTO game_data (user_id, game_id, account_id) VALUES ('6', '4', '4');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('4', 'AMZN', '5');

INSERT INTO users (email,username,password_hash,role) VALUES('user5@mail.com','user5','$2a$10$00EgXZjMj7RVp.m1JyeL2enD3p8WJU5BD7PJeWivUxWjRutq2bZg.','ROLE_USER');
INSERT INTO game (game_name, organizer_id, start_date, end_date) VALUES ('game5', '7', '2022/02/07', '2022/02/15');
INSERT INTO account (user_balance, stock_value, dollar_amount) VALUES ('100000', '0', '100000');
INSERT INTO game_data (user_id, game_id, account_id) VALUES ('7', '5', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('5', 'AAPL', '5');

INSERT INTO account (user_balance, stock_value, dollar_amount) VALUES ('100000', '0', '100000');
INSERT INTO game_data (user_id, game_id, account_id) VALUES ('3', '2', '6');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'AAPL', '20');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'V', '20');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'CSCO', '25');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'MSFT', '30');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'VOD', '50');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'NVDA', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'INTC', '90');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'ORCL', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'GOOGL', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'AMZN', '7');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'TSM', '12');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'FB', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'KO', '24');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'BABA', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'CVX', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('6', 'JPM', '15');
UPDATE account SET (user_balance, stock_value, dollar_amount) = ('104117.66', '74267.21', '29850.45') WHERE account_id = '6';

INSERT INTO account (user_balance, stock_value, dollar_amount) VALUES ('100000', '0', '100000');
INSERT INTO game_data (user_id, game_id, account_id) VALUES ('3', '3', '7');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'AAPL', '20');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'V', '20');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'CSCO', '25');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'MSFT', '30');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'VOD', '50');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'NVDA', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'INTC', '90');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'ORCL', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'GOOGL', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'AMZN', '7');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'TSM', '12');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'FB', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'KO', '24');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'BABA', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'CVX', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('7', 'JPM', '15');
UPDATE account SET (user_balance, stock_value, dollar_amount) = ('104117.66', '74267.21', '29850.45') WHERE account_id = '7';

INSERT INTO invite (user_id, game_id, accepted) VALUES ('3', '4', 'false');
INSERT INTO invite (user_id, game_id, accepted) VALUES ('3', '5', 'false');

INSERT INTO account (user_balance, stock_value, dollar_amount) VALUES ('100000', '0', '100000');
INSERT INTO game_data (user_id, game_id, account_id) VALUES ('4', '1', '8');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'AAPL', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'V', '18');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'CSCO', '30');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'MSFT', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'VOD', '45');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'NVDA', '12');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'INTC', '50');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'ORCL', '18');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'GOOGL', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'AMZN', '7');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'TSM', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'FB', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'KO', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'BABA', '12');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'CVX', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('8', 'JPM', '18');
UPDATE account SET (user_balance, stock_value, dollar_amount) = ('106394.90', '80921.92', '25474.45') WHERE account_id = '8';


INSERT INTO account (user_balance, stock_value, dollar_amount) VALUES ('100000', '0', '100000');
INSERT INTO game_data (user_id, game_id, account_id) VALUES ('4', '5', '9');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'AAPL', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'V', '18');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'CSCO', '30');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'MSFT', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'VOD', '45');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'NVDA', '12');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'INTC', '50');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'ORCL', '18');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'GOOGL', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'AMZN', '7');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'TSM', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'FB', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'KO', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'BABA', '12');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'CVX', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('1', 'JPM', '18');
UPDATE account SET (user_balance, stock_value, dollar_amount) = ('106394.90', '80921.92', '25474.45') WHERE account_id = '9';

INSERT INTO invite (user_id, game_id, accepted) VALUES ('4', '3', 'false');
INSERT INTO invite (user_id, game_id, accepted) VALUES ('4', '4', 'false');


INSERT INTO account (user_balance, stock_value, dollar_amount) VALUES ('100000', '0', '100000');
INSERT INTO game_data (user_id, game_id, account_id) VALUES ('5', '4', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'AAPL', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'V', '36');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'CSCO', '16');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'MSFT', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'VOD', '40');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'NVDA', '20');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'INTC', '35');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'ORCL', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'GOOGL', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'AMZN', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'TSM', '11');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'FB', '7');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'KO', '18');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'BABA', '9');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'CVX', '13');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'ADBE', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('10', 'JPM', '10');
UPDATE account SET (user_balance, stock_value, dollar_amount) = ('101576.68', '79985.20', '21586.83') WHERE account_id = '10';


INSERT INTO account (user_balance, stock_value, dollar_amount) VALUES ('100000', '0', '100000');
INSERT INTO game_data (user_id, game_id, account_id) VALUES ('5', '5', '11');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'AAPL', '15');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'V', '36');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'CSCO', '16');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'MSFT', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'VOD', '40');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'NVDA', '20');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'INTC', '35');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'ORCL', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'GOOGL', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'AMZN', '10');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'TSM', '11');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'FB', '7');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'KO', '18');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'BABA', '9');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'CVX', '13');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'ADBE', '5');
INSERT INTO stock_amount (account_id, stock_symbol, total_shares) VALUES ('11', 'JPM', '10');
UPDATE account SET (user_balance, stock_value, dollar_amount) = ('101576.68', '79985.20', '21586.83') WHERE account_id = '11';
INSERT INTO invite (user_id, game_id, accepted) VALUES ('5', '1', 'false');
INSERT INTO invite (user_id, game_id, accepted) VALUES ('5', '2', 'false');